### PR TITLE
add argmin and argmax

### PR DESCRIPTION
**Pull request by AlexKnauth**

### CODE REVIEW

**Comment by lexi-lambda** [comment]
I'm a fan of the idea, but I'm less sure about the names—`argmin` and `argmax` are a bit cryptic, even if that's what they're called in Racket. Clojure calls these `max-key` and `min-key`, which are better, but I don't think they're perfect. Any ideas?

**Comment by AlexKnauth** [comment]
It returns the element with the minimum/maximum value of f. The `arg` doesn't fit, the `key` seems to imply dict keys, and it has to have something to let people know it's not just `(max ...)` or `(apply max ...)`. I don't know what though.

**Comment by lexi-lambda** [comment]
What about `min-map` and `max-map` to mirror how `andmap` and `ormap` work?

**Comment by AlexKnauth** [comment]
I think that would work. Do you want me to rename them? Should it be `min-map` or `minmap`?

**Comment by AlexKnauth** [comment]
Actually maybe not, since it returns the element of the sequence, not the value. So it's more like a find than a map.

**Comment by lexi-lambda** [comment]
Hmm, you're right. That makes Clojure's naming make sense to me, now, but I'm still not sure it's the best. What about `find-min` and `find-max`, then?

As an aside, I prefer hyphenation when obvious. Maybe I should rename `andmap` and `ormap`, now that I think about it.

**Comment by AlexKnauth** [comment]
Just renamed to `find-min` and `find-max`.

**Comment by lexi-lambda** [comment]
Thanks! Now for a bit of code review.

I noticed you implemented this using `argmin` and `argmax`. I think it would be nicer to implement it in terms of `foldl` so that we don't need to copy the whole sequence to a list. It should be pretty trivial to implement.

Otherwise, thanks a lot! This looks like a great addition.

**Comment by AlexKnauth** [comment]
I reimplemented it using `for/fold` instead, because it needs two accumulator variables, one for the current best element, and one for the value of proc on that element.

**Comment by lexi-lambda** [comment]
Looks great. While I was driving home, I had some thoughts:
- Would it be better to, instead of providing a procedure that accepts an element and returns a real number, provide a `<` procedure, like you provide to `sort`? This would be much more flexible than only operating on numbers.
- If we do go with this, could you mention in the docs what happens when two values are equal?

**Comment by AlexKnauth** [comment]
Are you talking about something like this?

``` racket
> (best '((3 pears) (1 banana) (2 apples)) < #:key car)
'(1 banana)
> (best '((3 pears) (1 banana) (2 apples)) > #:key car)
'(3 pears)
> (define (find-min proc seq)
    (best seq < #:key proc))
> (define (find-max proc seq)
    (best seq > #:key proc))
```

Is that what you mean?
(By the way I just copied the argument order, including the `#:key` keyword, from `sort`.)

**Comment by lexi-lambda** [comment]
Yes, that's the sort of thing I'm referring to. If we _do_ go down that path, though, I think the argument order should be changed to take the less-than function before the sequence to make it easier to partially apply, just like I already did with `take` and `drop`.

**Comment by AlexKnauth** [comment]
Ok. Should the argument order be `(best proc <? seq)`, `(best <? proc seq)`, `(best <? seq #:key proc)`, or something else? Also, is `best` the best name for this?

**Comment by AlexKnauth** [comment]
Just added it as `(find-best <? proc seq)`. That way `find-min` and `find-max` are equivalent to `(partial find-best <)`, and `(partial find-best >)`.

**Comment by lexi-lambda** [comment]
I'm not sure that `find-min` and `find-max` are necessary with this (they're overly-specific, and they don't save much typing). What about renaming `find-best` to `find-max` and defining `find-min` as `(find-max (not <?) seq)`? Or would that cause problems due to the equality case?

**Comment by AlexKnauth** [comment]
The `argmin` and `argmax` functions always return the first element of the list that has the min or max, so that would mean `find-min` and `find-max` would no longer be consistent with that.

**Comment by AlexKnauth** [comment]
Also, to me, max and min are for numbers, but best is more general, so I think `find-best` is a better name for the generalized function than `find-max`.

**Comment by lexi-lambda** [comment]
You're right... can we find a better name than `find-best` that is number- and direction-agnostic? Something like `first-sort` or `first-ordered`? I don't like either of those names very much, but you get the point.

I still don't think `(curry <our-optimization-fn> <)` needs to be in the standard library. It is easy to build with basic functional programming concepts.

**Comment by AlexKnauth** [comment]
For code clarity, I think it does. `find-min` and `find-max` are very clear about min and max, but `(curry find-best <)` isn't as clear about that.

**Comment by lexi-lambda** [comment]
That's true, but in those cases, a simple `(apply max seq)` works. If necessary, `(apply max (map f seq))`. Still, feature-full libraries are good... I'd be okay with having `find-min` and `find-max`, but I still think we need a good name for `find-best`.

**Comment by AlexKnauth** [comment]
No, it doesn't. It returns not the max or the min, but the element of the original sequence that gave the max or min value. That's why it's a find function instead of a `max-map` function.

**Comment by lexi-lambda** [comment]
Yes, yes. I'm okay with having those aliases built-in. But `find-best` is not a good name.

**Comment by AlexKnauth** [comment]
Why not? I think it makes perfect sense. It's the max if it's the best at being greater than other things, and it's the min if it's the best at being less than other things.

**Comment by lexi-lambda** [comment]
It's far too opinionated. What if I'm specifically trying to find the _lowest_ number for something, and I'm optimizing for the worst case? The name has potential to be too confusing because it isn't general enough.

**Comment by AlexKnauth** [comment]
Would `find-extreme` be better then? I like `best` because I like the analogy between "max" and "best at being greater than others" and "min" and "best at being less than others," but I see how that could be confusing in some cases. So since extreme can mean best or worst, is that better? It doesn't feel right though.

**Comment by AlexKnauth** [comment]
For best, maybe it's not that it returns the best value, but the best thing to return, where you tell it how to determine the best thing to return. At least that's how I think of it. If the worst one is the one you want, then that's the best thing to return.

**Comment by AlexKnauth** [comment]
Would `find-most-relevant` work?

**Comment by lexi-lambda** [comment]
Seems wordy. Maybe we should ask the mailing list?

**Comment by AlexKnauth** [comment]
What do you think of `find-optimal`?

**Comment by AlexKnauth** [comment]
?

**Comment by AlexKnauth** [comment]
`first-by` ?

**Comment by AlexKnauth** [comment]
moved to https://github.com/lexi-lambda/racket-collections/pull/1

**Pull request closed without merging**
