### PR TITLE
add cartesian-product

### PR DESCRIPTION
**Pull request by AlexKnauth**

### CODE REVIEW

**Comment by lexi-lambda** [comment]
This is a great addition. One thing of note: I'm familiar with the "FOIL" acronym, but I don't think it's all that general, and I'm not sure if it's good terminology to use here, especially since this is variadic. Also, could you remove the assertion comments above the implementation?

**Comment by AlexKnauth** [comment]
Even though the acronym doesn't apply, I still think of `(* (+ a) (+ b c) (+ 1 2 3)) -> (+ (* a b 1) (* a b 2) (* a b 3) (* a c 1) (* a c 2) (* a c 3))` as foiling. Really it's repeated distributive property, but foiling is shorter and easier to say, and it's really the same process, just generalized a bit. And I think those comments are really helpful in saying what this thing actually does, which isn't clear at all from the implementation.

**Comment by AlexKnauth** [comment]
I replaced those with one example that doesn't use check-equal? or any concrete syntax, but that I think does better at getting the point across.

**Comment by lexi-lambda** [comment]
I will respectfully disagree. I think "foil" is a term exclusively used in (relatively) early academics that isn't terribly well-known outside of that, but "cartesian product" is a well-defined term that everyone knows. I would like to keep things simple in that regard—maybe just link to [the Wikipedia entry for Cartesian product](https://en.wikipedia.org/wiki/Cartesian_product)?

**Comment by AlexKnauth** [comment]
Ok. In algebra and calculus class, we regularly talked about "foiling it out" even for the generalized case, but I had never heard of a cartesian product until I came across this function. But maybe I just came from a weird school. I'll replace it with the link.

**Comment by lexi-lambda** [comment]
Well, yes, that was more or less my point: FOIL refers to a very specific case, which is binomial expansion. It's a mnemonic used in teaching distributed multiplication. I agree that cartesian product is a less generally-known term, but I think it is well-known amongst mathematicians and, most importantly, computer scientists and programmers.

**Comment by AlexKnauth** [comment]
Yes I know. Just did that.

**Comment by AlexKnauth** [comment]
First, just to be clear, you are right, and I did what you asked.
But in case you misunderstood me, I meant that we almost forgot that F O I L actually stood for something and used "foil" to refer to everything that mathematicians would mean by cartesian product. When we said "foil it out," we didn't FOIL it out, we did the generalized every combination thing that the cartesian product does. Our word "foil" was no longer tied to the acronym F O I L. But after finding that function, I became aware that there is a correct term for that, and that term is Cartesian product. But when I hear Cartesian product, I think of foiling, not FOILing. 

``` racket
#lang my-brain
(define FOIL (I-forget))
(define foil (what-everyone-else-calls "Cartesian product"))
(define cartesian-product (oh-you-mean foil))
(check-equal? FOIL "what's that again?")
```

I just thought "foiling" would be a good way to trigger thoughts about this for people like me and my high-school classmates who have heard of this thing that everyone else has a technical term for, but don't know the technical term. But I took your advice and put a link instead.

**Comment by lexi-lambda** [comment]
Merged in 42aaad8dc8ad4b88490fdfc0d3a8347874d7e584.

**Pull request closed without merging**
